version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-container
    ports:
      -  "4000:4000"
    networks:
      -  app-network

  user-client:
    build:
      context: ./client/user
      dockerfile: Dockerfile
    container_name: user-container
    depends_on:
      -  server
    ports:
      -  "5173:5173"
    networks:
      -  app-network

  admin-client:
    build:
      context: ./client/admin
      dockerfile: Dockerfile
    container_name: admin-container
    depends_on:
      -  server
    env_file: ./client/admin/.env
    ports:
      -  "3000:3000"
    networks:
      -  app-network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    restart: unless-stopped
    depends_on:
      -  server
      -  admin-client
      -  user-client
    volumes:
      -  ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Привязка конфига к контейнеру
      -  etc-letsencrypt:/etc/letsencrypt
      -  www-certbot:/var/www/certbot
    ports:
      -  "80:80"
      -  "443:443"
    networks:
      -  app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      -  nginx
    volumes:
      -  etc-letsencrypt:/etc/letsencrypt
      -  www-certbot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email nakadashi@mail.ru --agree-tos --no-eff-email -d exchange-app-prj.ru

volumes:	# Общие тома для nginx и certbot
  www-certbot:
  etc-letsencrypt:

networks:
  app-network:  # Сеть контейнеров
    driver: bridge    

# Запуск
# docker-compose up -d

